### ISSUE TITLE
车万女仆mod的运行异常问题

### ISSUE THREAD

**Issue by Galaxyapathy** [Loli-Server/LoliServer#1]
1.16.5的车万女仆mod无法在LoliServer上正常运行，女仆受到攻击后不会被击退，也不会闪红，死亡也不会掉落胶片
已去除过所有其他mod和插件，但仍然无法正常运行，故不是其他mod或插件的影响导致的
且在单人模式下该mod一切正常，可以断定LoliServer核心不兼容该mod，希望开发者可以尽快修复这个问题

**Comment by Kotori0629** [comment]
请将Issues提交至 https://github.com/Luohuayu/CatServer/issues
