### ISSUE TITLE
无法在LoliServer中找到Loli

### ISSUE THREAD

**Issue by KomiMoe** [Loli-Server/LoliServer#12]

**Comment by Kotori0629** [comment]
Could not load event LoliSearchEvent
cause by: java.lang.Nullpointexception
![QQ图片20210418145223](https://user-images.githubusercontent.com/81866089/115136961-cf914300-a055-11eb-8426-fad975560d7b.jpg)

**Comment by heipiao233** [comment]
Loli loli = LoliServer.getInstance().getLoli()
java.lang.NoSuchMethodException: LoliServer.getLoli
改了一下
Loli loli = new Loli()
java.lang.ClassNotFoundException: Loli
