### ISSUE TITLE
BetonBoxs Addons BSkyBlock error

### ISSUE THREAD

**Issue by Kotori0629** [Loli-Server/LoliServer#13]
https://paste.ubuntu.com/p/6ckfQqJNjr/

**Comment by piccup** [comment]
好耶

**Comment by Kotori0629** [comment]
fix from: [https://github.com/Loli-Server/LoliServer/commit/25072cc28f6f6a5c3b034e113719d9b5732c73d7](url)

**Comment by Kotori0629** [comment]
Download last successful build. Fixed.
