### ISSUE TITLE
[plugins] PlayerDataSql 部分功能不兼容

### ISSUE THREAD

**Issue by MrLyyy** [Loli-Server/LoliServer#14]
模块 Minecraft原版数据 在序列化 Shuoshur 的数据时发生了错误
Shuoshur为玩家
https://paste.ubuntu.com/p/TDPDN3vJZH/

**Comment by KomiMoe** [comment]
请确认PaperSpigot能正常使用

**Comment by MrLyyy** [comment]
可以

**Comment by NekohaShizuku0** [comment]
完整日志?

**Comment by Kotori0629** [comment]
update to lastSuccessful version. ——LoliServer
