### ISSUE TITLE
[MOD]supplementaries加入后崩服

### ISSUE THREAD

**Issue by 864063334** [Loli-Server/LoliServer#16]
MOD列表：supplementaries
插件：无
最新版本服务端
MOD下载：
https://yun.balala.club/uploads/1/3.13/plun/2021/04/%5B%E5%8E%9F%E7%89%88%E6%89%A9%E5%85%85%5Dsupplementaries-1.16.5-0.12.0.jar
崩服日志
https://yun.balala.club/uploads/1/3.13/plun/2021/04/latest.log

**Comment by Kotori0629** [comment]
Update to lastSuccessful build ——LoliServer
