### ISSUE TITLE
部分物品从创造物品栏拿出导致NBT丢失

### ISSUE THREAD

**Issue by hu7x** [Loli-Server/LoliServer#18]
### **问题描述**
部分物品从创造物品栏或从地牢奖励箱拿出时导致NBT丢失
目前已知有这个BUG的物品有夸克(Quark)的古卷 冠军(Champions)的刷怪蛋
### **复现方法**
从创造物品栏**拿出**该物品即可（数字键拿出不会影响 但一旦切换物品位置还会出现上述特性）
MOD链接 :
夸克：https://www.curseforge.com/minecraft/mc-mods/quark
冠军：http://www.curseforge.com/minecraft/mc-mods/champions
使用的MOD和客户端皆为最新版本
单机/Forge官服均无此特性出现
PS:这原本是墨端一开始就有的一个老特性（隔壁螺端貌似也有）不过有一阵子蘑菇蓝失踪导致不能用中文反馈漏洞就把这BUG忘了....
当然也不排除有可能MOD作者的锅（

**Comment by Kotori0629** [comment]
请测试原版forge服务端是否出现此Bug

**Comment by hu7x** [comment]
> 请测试原版forge服务端是否出现此Bug
??我上面不是写了官服forge没这个特性
另外重新测试了下 最新版本的螺端已经修复了这个特性

**Comment by Kotori0629** [comment]
Fixed . [https://github.com/Loli-Server/LoliServer/commit/8558cde1f2dd9b9dc4facdba2cc9d9aff1f039b4](url)
