### ISSUE TITLE
CorailTombstone在死亡时未正确生成墓碑

### ISSUE THREAD

**Issue by nenglizuida** [Loli-Server/LoliServer#21]
CorailTombstone[Corail的墓碑]在 LoliServer-1.16.5.56cf3a0-server 版本中 玩家死亡时无法正确生成墓碑 但灵魂状态任然拥有

**Comment by Kotori0629** [comment]
Fixed . [https://github.com/Loli-Server/LoliServer/commit/e05b3a0019119f1070dfdc2836bf390d5c151cab](url)
