### ISSUE TITLE
冰与火之歌mod所有龙击杀不掉掉落物

### ISSUE THREAD

**Issue by piccup** [Loli-Server/LoliServer#22]
在创造模式拿出生成龙的怪物蛋，生存模式或者创造模式击杀龙后,龙变成尸体，玩家右键尸体，不掉掉落物。
在主世界自然生程的龙尸体，右键不掉掉落物 。
forge复现则掉落
无报错现象
插件无
服务器版本 LoliServer-1.16.5-3650593-server.jar

**Comment by Kotori0629** [comment]
Fixed
