### ISSUE TITLE
旅行者背包Traveller's Backpack 背包复制，与forge相关

### ISSUE THREAD

**Issue by ybquality** [Loli-Server/LoliServer#25]
MoHist版本：mohist-1.16.5-528-server
模组：旅行者背包TravelersBackpack-1.16.5-5.4.1 
模组地址：https://www.curseforge.com/minecraft/mc-mods/travelers-backpack
情况描述：
在开启死亡掉落的情况下，
原模组佩戴背包在死亡后会在死亡地生成一个放置在放块上的背包，如死亡地无放置位置则正常掉落；
使用mohist及基于mohist的loliserver中该模组在封闭空间中死亡且检测不到背包放置地的情况下会多生成一份与原背包相同的背包（背包属性、背包内物品都相同）。
使用Arclight服务端测试未出现该问题，初步猜测未forge问题。

**Comment by Kotori0629** [comment]
Fixed this commits: [https://github.com/Loli-Server/LoliServer/commit/78b1eff8df92bd24fbb65e29319844d46c798aa4](url)
