### ISSUE TITLE
无法使用WorldEdit

### ISSUE THREAD

**Issue by In77** [Loli-Server/LoliServer#27]
### WorldEdit Bukkit 和 Forge 版均无法在LoliServer使用

服务端版本: _LoliServer version 1.16.5-f40884b (MC: 1.16.5)_
服务器OS&Java: _Debian 10, OpenJDK 11_

**Bukkit版WE: 插件加载出错并无法使用**
测试过的WE版本: _Bukkit 7.2.2, 7.2.5_

- 插件加载时无法载入 bukkit adapter
[https://pastebin.ubuntu.com/p/8R64pqxyYS/](https://pastebin.ubuntu.com/p/8R64pqxyYS/)

- 指令使用时报错: [https://pastebin.ubuntu.com/p/6x6S6Q9Wby/](https://pastebin.ubuntu.com/p/6x6S6Q9Wby/)

**Forge版WE: 在服务器使用时无法使用指令,显示未知命令**
测试过的WE版本: _Forge 7.2.5_

服务器可以加载Forge版WorldEdit
*客户端也安装有WE
木斧可以选择区域, 但使用WE指令时(包括客户端与服务端)服务器提示Unknown command

**Comment by Kotori0629** [comment]
Forge版本WorldEdit：你需要在服务端安装后 在客户端安装一份.  
Bukkit版本WorldEdit：等待修复.

**Comment by In77** [comment]
> Forge版本WorldEdit：你需要在服务端安装后 在客户端安装一份.
*测试时客户端与服务器均安装WorldEdit Forge

**Comment by Kotori0629** [comment]
> 
> 
> > Forge版本WorldEdit：你需要在服务端安装后 在客户端安装一份.
> > *测试时客户端与服务器均安装WorldEdit Forge

或许摸摸萝莉头头就可以解决了

**Comment by Kotori0629** [comment]
Roll back worldedit to 7.2.0

**Comment by Kotori0629** [comment]
Fixed
