### ISSUE TITLE
关于world游戏规则设置问题

### ISSUE THREAD

**Issue by liaojinmin** [Loli-Server/LoliServer#28]
在使用如何基础插件/原板指令修改对应世界规则时，是有效的，可一旦重启，使用规则恢复默认，导致部分设置无法进行。极大影响列如服务器主城世界的一些设置。

**Comment by Kotori0629** [comment]
LoliServer Version: 1.16.5-dd054d5 
The problem you described has not been reproduced, perhaps due to the plug-in
