### ISSUE TITLE
夸克模组的Totem of Holding功能没有作用

### ISSUE THREAD

**Issue by H1de0nbush** [Loli-Server/LoliServer#30]
Totem of Holding是Quark Oddities带的一个死亡墓碑功能，玩家死亡后会生成一个悬浮的图标，玩家可以通过点击取回死亡时的物品。
在客户端上运行正常，但是在服务器上无论是LoliServer还是Mohist都无法正常生成墓碑，玩家死亡后跟原版一样东西掉落在地上。
服务器核心和mod都是最新版的.
mod:
[https://www.curseforge.com/minecraft/mc-mods/quark](url)
[https://www.curseforge.com/minecraft/mc-mods/quark-oddities](url)
log:
[https://drive.google.com/file/d/1818kh5hpNZ1fmMt_34bUcHWwnf2U97hB/view?usp=sharing](url)

**Comment by Kotori0629** [comment]
em 在log中没看到任何错误报告

**Comment by H1de0nbush** [comment]
可能是什么玄学bug吧.我当时也自己翻了下log找不到什么问题...在夸克那边提issue了也还没有回应。应该是mod的服务器兼容问题吧...

**Comment by Kotori0629** [comment]
反映较多再考虑修复

**Comment by H1de0nbush** [comment]
我在Quark那边也反映了，作者说是mohist的问题🤔

**Comment by Kotori0629** [comment]
是的， 在融合Bukkit/CraftBukkit后可能出现
