### ISSUE TITLE
[1.16] FartherViewDance plugin

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer#305]
**Minecraft Version(我的世界版本) :** 1 16

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-365338e-server.jar"

**Operating System(操作系统) :** Windows 10
**Concerned mod / plugin(有关的插件/Mod) :** Only  FartherViewDistance 8.4.10, ProtocolLib 4.6.0
https://www.spigotmc.org/resources/fartherviewdistance.84950/
https://github.com/dmulloy2/ProtocolLib/releases/download/4.6.0/ProtocolLib.jar

**Logs :** [Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
](https://paste.loliidc.cn/?d37f5020b9ffaa7b#5kgx5mUBGhxqcVLBJn8pZDupPURpMNf5KrAWScS8i9P7)
**Steps to Reproduce(复现步骤) :**
 1. Install protocllib and FatherViewDistance 
 2. start the server and wait for it to start completely
 3. **server-tick-max-generate-amount to 0 and read-server-loaded-chunk to false** in config FatherViewDistance 
4. Start server Start the server and fly around the world, sometimes you can meet warnings in the world

**Description of issue :** First of all, I reported this error to the author himself, but he could not reproduce it on Spigot 1.16.5
![image](https://user-images.githubusercontent.com/86433158/146764838-881950a1-9be6-440a-8337-7736e81b8400.png)

mostly when loading the world, strange warnings are created, but the plugin fulfills its role perfectly

**Comment by XionioXMaster** [comment]
stop server
https://paste.loliidc.cn/?421d895d145df511#9SpaCE45oakYciGxLf82HeBPGJZchx1dv7u2zMYZoQ1r

**Comment by DonorKrovi** [comment]
This plugin does not work, for example, if I go to the server, the chunks that I downloaded will no longer be sent to the client
