### ISSUE TITLE
[1.16] 使用FTB模组，领地权限出现问题。

### ISSUE THREAD

**Issue by EnterFor** [Loli-Server/LoliServer#307]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-2d5d3f0-server.jar"

**Operating System(操作系统) :** Windows Server 2019

**Concerned mod / plugin(有关的插件/Mod) :** FTB Chunk丨FTB Team丨FTB Quests

**Logs :** 日志中没有任何错误显示

**Steps to Reproduce(复现步骤) :**
1.安装FTB家族Mod
2.玩家A创建队伍，圈好地，邀请玩家B进组（玩家B这时有权限，可以交互方块）
3.服务器重启，玩家B的权限消失（但是还显示在队伍中）
4.临时解决办法，每次重启后删除FTB的圈地数据
题外：默认玩家只能使用创建队伍的指令，“同意进队”、“离开队伍”等指令都不能使用，提示没有使用指令的权限，默认不应该这样，我必须手动添加ftbteam的权限节点，可以暂时解决。

**Description of issue :** 出现这种问题没有任何错误显示

我不知道是哪个Mod引发的
https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge
https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge
https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge

我的Mod列表和插件列表，希望可以起到帮助
![image](https://user-images.githubusercontent.com/10114685/147377704-86bfda65-a268-49d7-92b4-c7683dbe239f.png)
![image](https://user-images.githubusercontent.com/10114685/147377720-b294e587-5336-4c1e-b433-eb5e7d6924b6.png)

**Comment by Kotori0629** [comment]
还是建议使用Bukkit系插件

**Comment by Kotori0629** [comment]
无法修复
