### ISSUE TITLE
[1.16] Quark mod server delay when unlocking recipes for a player

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer#310]
**Minecraft Version(我的世界版本) :**  1 16
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-******-server.jar](https://github.com/Loli-Server/LoliServer/actions/runs/1633375279)"

**Operating System(操作系统) :** unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** Quark, better nether reforge, better nether forge

**Logs :** nope

**Steps to Reproduce(复现步骤) :**
 1. Install Quark and start server
 2. To see the delay, you can watch the TPS during the call

**Description of issue :** The error occurs when a new player joins the server, I found the cause of this error! This is Quark's ability to give the player all crafting recipes from mods, there may be a 5-10 seconds delay during the issuance of these recipes, depending on the number of mods in the assembly!

In order to notice the delay, enter the server with 2 players, 1 player will be able to notice how all entities will freeze for 3-4 seconds while recipes are issued to 2 players

still the delay depends on mods with a lot of recipes

**Comment by Kotori0629** [comment]
I don't understand what you are saying.. Can you give me a video？

**Comment by XionioXMaster** [comment]
> I don't understand what you are saying.. Can you give me a video？

It will take some time

**Comment by XionioXMaster** [comment]
https://github.com/VazkiiMods/Quark/issues/3531

Vazkii closed my topic without describing anything, it looks like it cannot be reproduced

I'll try to ask him on discord

**Comment by XionioXMaster** [comment]
Quark problem
