### ISSUE TITLE
[1.16] taterzens-1.1.0-forge mod crash

### ISSUE THREAD

**Issue by DonorKrovi** [Loli-Server/LoliServer#311]
**Minecraft Version(我的世界版本) :** 1 16
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-******-server.jar](https://github.com/Loli-Server/LoliServer/actions/runs/1629826828)"

**Operating System(操作系统) :** unbuntu 18

**Concerned mod / plugin(有关的插件/Mod) :** 
[taterzens-1.1.0-forge.zip](https://github.com/Loli-Server/LoliServer/files/7807677/taterzens-1.1.0-forge.zip)

**Logs :** [Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)](https://paste.loliidc.cn/?c449d2c39e7f4f6d#AfPpXXYNEYgJns6cekvfrKGeHp5E1Nnpqtc2mCdXF1My)

**Steps to Reproduce(复现步骤) :**
 1. start server 
 2. mod mod
 3. restart server

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/148181579-bd9c384b-4cab-4c9e-a712-5044b7910d38.png)
Are u sure?

**Comment by Kotori0629** [comment]
Give me your modpack

**Comment by XionioXMaster** [comment]
> yesterday
Sorry for not having time to give the modpack, just returned from work today

**Comment by Kotori0629** [comment]
> 

This bug is fixed
