### ISSUE TITLE
[1.16.5] 深度怪物学习 不加杀敌数

### ISSUE THREAD

**Issue by PAKingdom** [Loli-Server/LoliServer#313]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-ccb19cf-server.jar"

**Operating System(操作系统) :** ubuntu 20 TLS

**Concerned mod / plugin(有关的插件/Mod) :** 深度怪物学习[hostile-neural-networks]https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks

**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)

**Steps to Reproduce(复现步骤) :**
 1. 在ATM6 
AllTheMods 6-1.8.16版本上使用
2.深度学习器 (Deep Learner)在物品栏时造成怪物击杀无数值变动
(就是不算击杀数)
 

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
毫无错误报告？

**Comment by PAKingdom** [comment]
> 无错误报告？

无

**Comment by PAKingdom** [comment]
https://user-images.githubusercontent.com/68528277/148680507-26413e2a-8335-40de-b4c2-95e86b3ab1c9.mp4

**Comment by Xplodin** [comment]
I too have this exact issue with atm6 and its definitely not the mod cause it works normally without the software

**Comment by Xplodin** [comment]
It seems the error has fixed or stopped.
I no longer have this issue with the newest atm6 update
