### ISSUE TITLE
[1.16] 关于RealSurvival插件与Loliserver兼容问题 

### ISSUE THREAD

**Issue by xiaotangaa** [Loli-Server/LoliServer#314]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-ccb19cf-server

**Operating System(操作系统) :Windows

**Concerned mod / plugin(有关的插件/Mod) :RealSurvival

**Logs :https://paste.loliidc.cn/?9c66d9e5e40be282#3435RMUFpEz7m2fc2oYuy2VarZ8MPmFQufLA4wiP1MeN

**Steps to Reproduce(复现步骤) :**
 1. 开服加载即报错

**Description of issue :** Give all details about your issue

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/161258094-f03b5f4b-f2ac-4d7e-a286-8350248f1398.png)
This plugin worked fine !
