### ISSUE TITLE
[1.16] Server freeze (maybe ice and fire)

### ISSUE THREAD

**Issue by bigenergy** [Loli-Server/LoliServer#315]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-ccb19cf-server

**Operating System(操作系统) :** ubuntu

**Concerned mod / plugin(有关的插件/Mod) :** maybe Ice and fire

**Logs :** https://gist.github.com/bigenergy/c248435609a9baa44c62b8d284491c48

**Description of issue :** Server freezing

**Comment by XionioXMaster** [comment]
https://paste.loliidc.cn/?9b38da5227d627da#8wQKf4H9Ro5954AkeTcBj5xctNoHDYh2rC1DU9pJUD9n

a few days ago I also reported this problem, I don't have ice and fire. I myself do not understand what this may be connected with

**Comment by Deviken** [comment]
turn off fast edit mode,and u'll be fine

**Comment by bigenergy** [comment]
> turn off fast edit mode,and u'll be fine

what mod are you talking about?

**Comment by XionioXMaster** [comment]
> 



> turn off fast edit mode,and u'll be fine

What does it mean?

**Comment by Deviken** [comment]
> 

for example,u prob have a .bat file to start ur server right?right-click on it and select properties,then u will see "fast edit mode".simply disable it to stop the server from freezing

**Comment by XionioXMaster** [comment]
> > 
> 
> for example,u prob have a .bat file to start ur server right?right-click on it and select properties,then u will see "fast edit mode".simply disable it to stop the server from freezing

dude this is bullshit
