### ISSUE TITLE
在服务核心启动过程中不久出现死循环报错,被迫使用stop后生成了文件,内容如下

### ISSUE THREAD

**Issue by 764069075** [Loli-Server/LoliServer#316]
---- Minecraft Crash Report ----
// Shall we play a game?

------------
# Chinese: 
// 如果你需要得到LoliServer开发组的帮助, 请通过Discord或者QQ联系我们, 或者: 
// Step 1: 提交这个Crashreport中的文本至 https://paste.ubuntu.com
// Step 2: 创建一个新的Issues至LoliServer的Github仓库, 地址: https://github.com/Loli-Server/LoliServer1.16/issues
# English and other: 
// If you need to LoliServer Development Group help, Contact us at discord or: 
// Step 1: Submit this CrashReport to https://paste.ubuntu.com/
// Step 2: Create a new issues to LoliServer's Github repos, Link: https://github.com/Loli-Server/LoliServer1.16/issues
------------

Time: 2022/1/13 上午1:25
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: Could not initialize class me.ultimategamer200.ultracolor.ultracolor.lib.remain.Remain
	at me.ultimategamer200.ultracolor.ultracolor.lib.Common.stripColors(Common.java:699) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
	at me.ultimategamer200.ultracolor.ultracolor.lib.plugin.FoundationFilter.isFiltered(FoundationFilter.java:68) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
	at me.ultimategamer200.ultracolor.ultracolor.lib.plugin.FilterLegacy.isLoggable(FoundationFilter.java:114) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading}
	at java.util.logging.Logger.log(Logger.java:965) ~[?:?] {}
	at java.util.logging.Logger.doLog(Logger.java:1006) ~[?:?] {}
	at java.util.logging.Logger.log(Logger.java:1117) ~[?:?] {}
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:311) ~[forge:?] {re:classloading}
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:298) ~[forge:1.16.5-ccb19cf] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:724) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:829) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	LoliServer Version: 1.16.5-ccb19cf
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 11.0.11, Alibaba
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Alibaba
	Memory: 2753753600 bytes (2626 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 12 total; -Xms4G -Xmx4G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/LoliServer-1.16.5-ccb19cf-server.jar object_holder_definalize PLUGINSERVICE 
		/LoliServer-1.16.5-ccb19cf-server.jar runtime_enum_extender PLUGINSERVICE 
		/LoliServer-1.16.5-ccb19cf-server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/LoliServer-1.16.5-ccb19cf-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/LoliServer-1.16.5-ccb19cf-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.22
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.22-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.4.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.5.4        |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.484-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.484   |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.1.456.jar               |Mekanism: Tools               |mekanismtools                 |10.1.1              |DONE      |Manifest: NOSIGNATURE
		architectury-1.27.45.jar                          |Architectury                  |architectury                  |1.27.45             |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.4-build.90.jar           |FTB Library                   |ftblibrary                    |1605.3.4-build.90   |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.1.456.jar          |Mekanism: Generators          |mekanismgenerators            |10.1.1              |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.139.jar                          |Just Enough Items             |jei                           |7.7.1.139           |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.1.jar                          |Botania                       |botania                       |1.16.5-420.1        |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.1.1.456.jar                    |Mekanism                      |mekanism                      |10.1.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.22-universal.jar                |Forge                         |forge                         |36.2.22             |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                           |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.6.8.jar                   |Curios API                    |curios                        |1.16.5-4.0.6.8      |DONE      |Manifest: NOSIGNATURE
		ExtraBotany-r1.2-68.jar                           |ExtraBotany                   |extrabotany                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		Neat 1.7-27.jar                                   |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 2c653f74-6c58-427c-bceb-463f4657d651
	CraftBukkit Information: 
   Running: LoliServer version 1.16.5-ccb19cf (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) false
   Plugins: { LuckPerms v5.3.89 me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin [Luck], Chunky v1.2.166 org.popcraft.chunky.ChunkyBukkit [pop4959], PlaceholderAPI v2.11.1 me.clip.placeholderapi.PlaceholderAPIPlugin [HelpChat], LaggRemover v2.0.6 drew6017.lr.main.LaggRemover [drew6017], ProtocolLib v4.7.0 com.comphenix.protocol.ProtocolLib [dmulloy2, comphenix], SimpleTpa v5.7* me.mulemuledupe.simpletpa.SimpleTpa [MuleMuleDupe], SkinsRestorer v14.1.10 net.skinsrestorer.bukkit.SkinsRestorer [Th3Tr0LLeR, McLive, DoNotSpamPls, knat, AlexProgrammerDE], LiteSignIn v1.5.5 studio.trc.bukkit.litesignin.Main [TRCStudioDean], Minepacks v2.4.3-Release at.pcgamingfreaks.Minepacks.Bukkit.MinepacksBadRabbit [GeorgH93], MPUtils v1.9.3 com.github.alfonsoleandro.mputils.MPUtils [lelesape], InventoryKeeper v2.1.1 me.starchier.inventorykeeper.InventoryKeeper [starchier], NBTAPI v2.8.0 de.tr7zw.nbtapi.plugin.NBTAPI [tr7zw], ServerListPlus v3.4.8* net.minecrell.serverlistplus.bukkit.BukkitPlugin [Minecrell <https://github.com/Minecrell>], Vault v1.7.3-b131 net.milkbowl.vault.Vault [cereal, Sleaker, mung3r], WorldEdit v7.2.8+6008-1246d61 com.sk89q.worldedit.bukkit.WorldEditPlugin [], LevelledMobs v3.3.2 b596 me.lokka30.levelledmobs.LevelledMobs [lokka30], TabooLib5 v5.66 io.izzel.taboolib.common.plugin.InternalJavaPlugin [坏黑], TrHologram v2.2 me.arasple.mc.trhologram.module.internal.boot.PluginBoot [Arasple], UltraColor v1.4.6 me.ultimategamer200.ultracolor.UltraColorPlugin [UltimateGamer200], GriefDefender v2.0.9 com.griefdefender.loader.BukkitLoaderPlugin [], XConomy v2.13.5 me.yic.xconomy.XConomy [YiC], GDHooks v0.5 com.griefdefender.hooks.loader.BukkitLoaderPlugin [], ChestSort v12.1.4 de.jeff_media.chestsort.ChestSortPlugin [mfnalex, JEFF Media GbR], Multiverse-Core v4.3.1-b861 com.onarandombox.MultiverseCore.MultiverseCore [dumptruckman, Rigby, fernferret, lithium3141, main--], Dantiao vEX-25 com.valorin.Main [Valorin], ChestCommands v4.0.3 me.filoghost.chestcommands.ChestCommands [],}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE Reference Handler: [java.base@11.0.11/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@11.0.11/java.lang.ref.Reference.processPendingReferences(Reference.java:241), java.base@11.0.11/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)], TIMED_WAITING TConfigWatcherService-1: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123), java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE Attach Listener: [], WAITING Snooper Timer: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.lang.Object.wait(Object.java:328), java.base@11.0.11/java.util.TimerThread.mainLoop(Timer.java:527), java.base@11.0.11/java.util.TimerThread.run(Timer.java:506)], TIMED_WAITING bStats-Metrics: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234), java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123), java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182), java.base@11.0.11/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE Server thread: [java.base@11.0.11/java.lang.Thread.dumpThreads(Native Method), java.base@11.0.11/java.lang.Thread.getAllStackTraces(Thread.java:1653), org.bukkit.craftbukkit.v1_16_R3.CraftCrashReport.call(CraftCrashReport.java:33), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:81), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:77), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:790), net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:264), net.minecraft.server.MinecraftServer$$Lambda$8421/0x000000080172f040.run(Unknown Source), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], RUNNABLE Signal Dispatcher: [], WAITING Worker-Bootstrap-3: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], RUNNABLE WindowsStreamPump: [app//org.fusesource.jansi.internal.Kernel32.WaitForSingleObject(Native Method), app//org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), app//org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:112), app//org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:458), app//org.jline.terminal.impl.AbstractWindowsTerminal$$Lambda$101/0x0000000800202c40.run(Unknown Source), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], WAITING modloading-worker-2: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], TIMED_WAITING Thread-0: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:357), app//com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:190)], WAITING ForkJoinPool.commonPool-worker-5: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], WAITING pool-10-thread-1: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.11/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114), java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], WAITING modloading-worker-0: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], TIMED_WAITING Spigot Watchdog Thread: [java.base@11.0.11/java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:104)], WAITING Log4j2-AsyncAppenderEventDispatcher-1-AsyncFile: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081), java.base@11.0.11/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417), app//org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), app//org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], TIMED_WAITING ObjectCleanerThread: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), app//io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54), app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], TIMED_WAITING Common-Cleaner: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.11/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148), java.base@11.0.11/java.lang.Thread.run(Thread.java:829), java.base@11.0.11/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)], RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], TIMED_WAITING Server console handler: [java.base@11.0.11/java.lang.Object.wait(Native Method), app//org.jline.utils.NonBlockingPumpReader.wait(NonBlockingPumpReader.java:55), app//org.jline.utils.NonBlockingPumpReader.read(NonBlockingPumpReader.java:101), app//org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), app//org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), app//org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), app//org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), app//org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), app//org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:60), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:96)], TIMED_WAITING Worker-Main-4: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], WAITING Worker-Main-5: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], TIMED_WAITING WorldEdit Session Manager: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.util.TimerThread.mainLoop(Timer.java:553), java.base@11.0.11/java.util.TimerThread.run(Timer.java:506)], RUNNABLE Netty Server IO #0: [java.base@11.0.11/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), java.base@11.0.11/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:357), java.base@11.0.11/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:182), java.base@11.0.11/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124), java.base@11.0.11/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:136), app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756), app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411), app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], WAITING Finalizer: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@11.0.11/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)], RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], TIMED_WAITING Timer hack thread: [java.base@11.0.11/java.lang.Thread.sleep(Native Method), net.minecraft.util.Util$6.run(Util.java:505)], RUNNABLE FileSystemWatchService: [java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus0(Native Method), java.base@11.0.11/sun.nio.fs.WindowsNativeDispatcher.GetQueuedCompletionStatus(WindowsNativeDispatcher.java:1036), java.base@11.0.11/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:587), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], TIMED_WAITING Worker-Bootstrap-2: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], RUNNABLE DestroyJavaVM: [], WAITING Java2D Disposer: [java.base@11.0.11/java.lang.Object.wait(Native Method), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@11.0.11/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.desktop@11.0.11/sun.java2d.Disposer.run(Disposer.java:144), java.base@11.0.11/java.lang.Thread.run(Thread.java:829)], TIMED_WAITING ForkJoinPool.commonPool-worker-7: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)], TIMED_WAITING modloading-worker-3: [java.base@11.0.11/jdk.internal.misc.Unsafe.park(Native Method), java.base@11.0.11/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275), java.base@11.0.11/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619), java.base@11.0.11/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)],}
   Recent tasks from -31--1{}
   Force Loaded Chunks: {}
	Player Count: 0 / 1000; []
	Data Packs: vanilla, mod:farmersdelight, mod:biomesoplenty, mod:mekanismtools, mod:architectury, mod:ftblibrary, mod:mekanismgenerators, mod:jei, mod:botania, mod:mekanism, mod:forge, mod:aquaculture (incompatible), mod:fastleafdecay, mod:curios, mod:extrabotany (incompatible), mod:twilightforest, mod:patchouli (incompatible), mod:neat (incompatible), mod:ctm (incompatible), file/bukkit
	Is Modded: Definitely; Server brand changed to 'LoliServer'
	Type: Dedicated Server (map_server.txt)

**Comment by Kotori0629** [comment]
把Ultracolor发来

**Comment by 764069075** [comment]
[Uploading UltraColor-1.4.6.jar…]()

**Comment by 764069075** [comment]
SPIGOTMC:
[https://www.spigotmc.org/resources/ultracolor.85332/](url)
[UltraColor-1.4.6.zip](https://github.com/Loli-Server/LoliServer/files/7859992/UltraColor-1.4.6.zip)
