### ISSUE TITLE
[BUG 1.16.5] WorldBorder disappears after server restart

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer#317]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** latest

**Operating System(操作系统) :** WIN 10

**Logs :** no logs

**Mod list(模组列表) :** none

**Plugin list(插件列表) :** none

**Description of issue(描述) :** hen I create a world border /worldborder set 500 (example), then I reboot the server and go to the world of the edge or hell, there is no world border.

**Comment by MrJorman** [comment]
Chinese, Korean or Japanese, as I understand it, you started ignoring us about the 1.16.5 core, that you can't fix the usual border of the world.

**Comment by Kotori0629** [comment]
> Chinese, Korean or Japanese, as I understand it, you started ignoring us about the 1.16.5 core, that you can't fix the usual border of the world.

Oh, welcome back, clown

**Comment by XionioXMaster** [comment]
Logs : no logs LMAO

Mod list(模组列表) : none ok

Plugin list(插件列表) : none ok

Although I know that you have a server with mods and even more so with plugins

**Comment by MrJorman** [comment]
> > Chinese, Korean or Japanese, as I understand it, you started ignoring us about the 1.16.5 core, that you can't fix the usual border of the world.
> 
> Oh, welcome back, clown

your mom - clown, fucking korean programmer boy, not enough brains to fix the border of the world
