### ISSUE TITLE
[1.16] CitizensCMD v2.5.1 plugin NoSuchMethodError

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer#322]
**Minecraft Version(我的世界版本) :** 1.16

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-******-server.jar](https://github.com/Loli-Server/LoliServer/actions/runs/1716595253)"

**Operating System(操作系统) :** unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible
[CitizensCMD.zip](https://github.com/Loli-Server/LoliServer/files/7899879/CitizensCMD.zip) + 
[FakePlayer.zip](https://github.com/Loli-Server/LoliServer/files/7899907/FakePlayer.zip)

**Logs :** [Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)](https://paste.loliidc.cn/?025f8cfcf684ee64#BBRqtFQFe3TAhufyhZDXdbhAuqvekYmg8a4U4v2qHnTF)

**Steps to Reproduce(复现步骤) :**
 1. start server and see console

**Comment by Kotori0629** [comment]
Contact the author
