### ISSUE TITLE
[1.16] Human Companions mods crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer#326]
**Minecraft Version(我的世界版本) :** 1 16

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "[LoliServer-1.16.5-******-server.jar](https://github.com/Loli-Server/LoliServer/actions/runs/1762205905)"

**Operating System(操作系统) :** Unbuntu 20

**Concerned mod / plugin(有关的插件/Mod) :** [Provide mod / plugin name and download link if possible](https://www.curseforge.com/minecraft/mc-mods/human-companions)

**Logs :** [Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)](https://paste.loliidc.cn/?5399a44225741304#9Ss34fFVSoKq9u36ix4ZqRHc8RnnSH3rufWGRYLdFJ22)

**Steps to Reproduce(复现步骤) :**
 1. Nothing complicated, just install and run the server

**Description of issue :** Works on the client without errors

**Comment by Kotori0629** [comment]
Contact mod author , this mod cannot work in forge_server
