### ISSUE TITLE
Illegal packet received, terminating connection

### ISSUE THREAD

**Issue by jia-qi1** [Loli-Server/LoliServer#327]
**Minecraft Version(我的世界版本) :** {Minecraft version}
1.16.5
**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}
LoliServer-1.16.5-cf5df2c-server
**Operating System(操作系统) :** {Provide the name of yo
Windows10
**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)
https://paste.loliidc.cn/?d94c5b41d8c8d7f8#7W5ju2XMgTerpavpMPBEhDTtyGiHVA4bYkwhQpbugUL6
**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}
Default, [前置]LibX-1.16.3-1.0.76.jar, [植物魔法全能工具]aiotbotania-1.16.5-1.8.4.jar, [畜牧业]Husbandry-1.16.5-1.0.4.jar, [MrCrayfish 的家具] cfm-7.0.0pre22-1.16.3.jar, [季节]Simply-Seasons-1.16.5-1.0.17.jar, [购物]Shopaholic-1.16.5-1.0.0.jar, [植物魔法]Botania-1.165-422.2.jar, [园艺]Horticulture-1.16.5-1.0.2.jar, [白天睡觉]Daydreamer-1.16.5-1.0.jar, forge-1.16.5-36.2.23-universal.jar, [企鹅]Waddles-1.16.5-0.8.13.jar, [捕鱼前置]Piscary-1.16.5-1.0.3.jar, [植物魔法前置]curios-API-forge-1.16.5-4.0.5.1.jar, [额外植物学]ExtraBotany-r1.2-68.jar, [帕秋莉手册植物魔法前置]Patchouli-1.16.4-53.2.jar, [丰收物语前置复制粘贴]copypaste-1.7.jar, [神话植物学] MythicBotany-1.16.5-1.4.19.jar, [丰收物语基础前置]Penguin-Lib-1.16.5-0.4.3.jar, bukkit
**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}
[Log4j修复]EastL andLog4Fixr-1....
[Lore编辑]Editlorejar
[NPC]itizens-2.0.27 b2297.jar
[TAB]TAB v2.8.10jar
[WE]Worldedit-bukkit-7.2.2-dist.jar
[变量]PlaceholderAPl-2.9.2jar
[菜单]ChestCommandsjar
[插件管理]Yumjar
[查崩]CoreProtect-19.5.jar
[称号]PlayerTitle-2.5.6jar
[地皮]PlotSquared-Bukkit-4.4.495.jar
[登录]CatSeedlogin-1.3.10-SNAPSOH0...
[掉落物清理]AdvancedCleaner-1.3.jar
[多世界]Multiverse-Core-4.2.2jar
[防爆]Boom-1.2.5.jar
[服务器图标]AdvancedNMotd-9.1.1.jar
[环球市场]CrazyAuctionsPlus-1.1.4.3jar
[基础插件]EssentialsX-2.19.0-dev+ 105...
[基础插件]EssentialsXChat-2.19.0-dev...
[基础插件]EssentialsXSpawn-2.19.0-...
[计分析InfiniteScoreboard-1.0.jar
[脚本方块]ScriptBlockPlus_ v.1.1jar
[脚本方块扩展]ScriptEntityPlus-master...
[禁用]Banltjar
[经济前置]Vault.jar
[控制台隐蔽]ConsoleSpamFix-1.8.5.jar
[领地]Residence4.9.3.4jar
[前置]item-nbt- api-pluginjar
[前置]ProtocolLibjar
[权限组]GroupManager [v3.3]jar
[全息]HolographicDisplaysjar
[杀怪掉钱]MoneyDropjar
[锁箱]Modern-LWC-2.1.5.jar
[箱子商店QuickShop-4.0.6.3jar
**Description of issue(描述) :** {Give all details about your issue}
服务器加了19个模组，客户端除了这19个之外加了几个客户端模组，最多加到25个，再多一个就会进不去，显示Illegal packet received, terminating connection或是连接终止之类的

**Comment by Kotori0629** [comment]
Remove [Log4j修复]EastL andLog4Fixr-1....

**Comment by jia-qi1** [comment]
Remove [log4j修复] eastl andlog4fixr-1. There was no effect。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Loli-Server/LoliServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 凌晨0:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Loli-Server/LoliServer] Illegal packet received, terminating connection (Issue #327)





 
Remove [Log4j修复]EastL andLog4Fixr-1....
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kotori0629** [comment]
排除法

**Comment by Kotori0629** [comment]
Mohist发我这里来干嘛 你去找Mohist 我又不是Mohist

**Comment by jia-qi1** [comment]
因为两个问题都是一样的，所以就都问了一下，两个我都试过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Loli-Server/LoliServer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 凌晨0:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Loli-Server/LoliServer] Illegal packet received, terminating connection (Issue #327)





 
Mohist发我这里来干嘛 你去找Mohist 我又不是Mohist
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kotori0629** [comment]
纯forge试试
