### ISSUE TITLE
[1.16] Core ignores some configs

### ISSUE THREAD

**Issue by Wishole** [Loli-Server/LoliServer#328]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :**  "LoliServer-1.16.5-b3d757c-server.jar"

**Operating System(操作系统) :** Windows 10 home 21H2

**Concerned mod / plugin(有关的插件/Mod) :** [Mystical Agriculture](https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture/files/3562127)

**Logs :** [latest.log](https://github.com/Loli-Server/LoliServer/files/7999060/latest.log) (starting the server)

**Steps to Reproduce(复现步骤) :**
 1. Changed the "secondarySeedDrops" parameter from "true" to "false"
 2. Logged into the game
 3. Harvested the crop to check if the setup is working

**Description of issue :** I noticed that the core ignores some configs (the problem was encountered in the "Gobber2", "Deadly And Phantoms" mods, but the most weighty in the "Mystical Agriculture" mod)
When the "secondarySeedDrops" parameter is turned off (and then restarted), the parameter behaves as if it is turned on.

I also checked on a regular Forge server, where everything was fine

**Comment by XionioXMaster** [comment]
Yes, the kernel doesn't ignore them, it flags configuration errors! To do this, you need to stop the server and change them, then start the server and they will work

**Comment by Wishole** [comment]
I didn't understand where to look for errors. Please explain 🙏
In the console I found only lines with Incorrect key

**Comment by Kotori0629** [comment]
I can't repeat what you said

**Comment by Wishole** [comment]
It turns out that the problem arose due to the conflict of mods "Quark" and "Croptopia" @_@
