### ISSUE TITLE
[1.16] Flan mod crash

### ISSUE THREAD

**Issue by XionioXMaster** [Loli-Server/LoliServer#334]
Minecraft Version(我的世界版本) : 1.16.5

LoliServer buildVersion(构建版本) : **The problem has been known since Provide** LoliServer-1.16.5-60-server.jar

Operating System(操作系统) : ubuntu 20

Concerned mod / plugin(有关的插件/Mod) : https://www.curseforge.com/minecraft/mc-mods/flan-forge

Logs : https://pastebin.com/DMA4gZ2x and https://pastebin.com/3KKbjdU1

Steps to Reproduce(复现步骤) :

Install https://www.curseforge.com/minecraft/mc-mods/flan-forge
Run server
Crash https://pastebin.com/DMA4gZ2x and https://pastebin.com/3KKbjdU1

**I already have a fairly large server where many players play and I began to notice problems that World Guard causes. For example, when saving all the privates in the world, there may be a delay of up to 30 seconds, apparently this is caused by mods. World Guard is difficult to compatible with new biomes and blocks in privates, which is why it saves all this longer,
and with problems

Flan's work is very important for servers as it provides best of its kind protection for mod servers from griefing!**

this Issuge copy:  https://github.com/Loli-Server/LoliServer/issues/132
https://github.com/Loli-Server/LoliServer/issues/91

**Comment by XionioXMaster** [comment]
In addition, sometimes players create a private in WorldGuard but are not the owners, this sometimes occurs in rare cases, which is why it is not clear why this happens. Flan is the best solution!

**Comment by Kotori0629** [comment]
#160 After fixed, same problem reproduce
