### ISSUE TITLE
[1.16.5]Forge-Carpet模组无法适配loliserver

### ISSUE THREAD

**Issue by warmsine** [Loli-Server/LoliServer#335]
在服务端LoliServer-1.16.5-185-server中
mod正常载入 指令无效
经过测试在官方forge端正常
另外，在官方forge端中任何玩家都可以正常使用指令，但在loliserver中，只有管理员能够使用。
不知何故，该指令被升级了权限等级。
此mod在mc百科中的链接：https://www.mcmod.cn/class/5135.html

**Comment by Kotori0629** [comment]
无法修复
