### ISSUE TITLE
Bukkit api issue (Some methods at Player class not working)

### ISSUE THREAD

**Issue by GDVE** [Loli-Server/LoliServer#336]
I use last build. I'm cheking bukkit api support and found problem with some methods:

1) org.bukkit.entity.Player.setPlayerWeather (works the other way around, for example, when WeatherType.DOWNFALL is specified, the weather becomes sunny, although it should rain for the player.)
2) org.bukkit.entity.Player.resetPlayerWeather (not working)

**Comment by GDVE** [comment]
Same problems with methods resetPlayerTime, setPlayerTime.

**Comment by GDVE** [comment]
![image](https://user-images.githubusercontent.com/19783608/152660933-2650b494-2037-4229-b04c-a747f35a0be9.png)
EssentialsX - /ptime command not working (plugin use this methods)

**Comment by Kotori0629** [comment]
Try use CMI

**Comment by Kotori0629** [comment]
I used CMI, cannot repeat this problem

**Comment by GDVE** [comment]
I dont know about CMI. What is it?

**Comment by Kotori0629** [comment]
> 

Search for : spigotmc.org

**Comment by GDVE** [comment]
It's paid, I don't want to buy it and it doesn't change the fact that the standard Bukkit method doesn't work.

**Comment by Kotori0629** [comment]
> It's paid, I don't want to buy it and it doesn't change the fact that the standard Bukkit method doesn't work.

Under my CMI test, this method works normally

**Comment by GDVE** [comment]
> > It's paid, I don't want to buy it and it doesn't change the fact that the standard Bukkit method doesn't work.
> 
> Under my CMI test, this method works normally

Please, check pweather command on CMI.

**Comment by GDVE** [comment]
CMI and Essentials use the same methods but the effect is different)

**Comment by Kotori0629** [comment]
`      if (type == WeatherType.DOWNFALL) {
         this.connection.send(new SChangeGameStatePacket(SChangeGameStatePacket.START_RAINING, 0));
      } else {
         this.connection.send(new SChangeGameStatePacket(SChangeGameStatePacket.STOP_RAINING, 0));
      }
   }`

**Comment by XionioXMaster** [comment]
CMI is the best for loli server, I use it exclusively

**Comment by GDVE** [comment]
> CMI is the best for loli server, I use it exclusively

I'm use self development core plugin for server. Essentials used only for tests. When writing, I thought that I wrote something wrong in my plugin :)
