### ISSUE TITLE
[1.16] 与Untamedwilds的兼容问题

### ISSUE THREAD

**Issue by hu7x** [Loli-Server/LoliServer#339]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) :LoliServer-1.16.5-b90f47b-server

**Operating System(操作系统) :WIN10

**Concerned mod / plugin(有关的插件/Mod) :[Untamedwilds-1.16.5-1.4.1](https://www.curseforge.com/minecraft/mc-mods/untamedwilds/files)

**Logs :https://paste.loliidc.cn/?c3656fe32423321f#2HPTSiF33CuPigSWr7TtjnnVYKDKgAbm22toaXicdPJv

**Steps to Reproduce(复现步骤) :
1.创造栏内找到该模组分栏
2.使用该模组的刷怪蛋（蜘蛛卵 蛇蛋 鱼卵）
3.无反应 后台报错

**Comment by Kotori0629** [comment]
forgeserver是否复现？
