### ISSUE TITLE
Flash back when the server is opened

### ISSUE THREAD

**Issue by Korniter** [Loli-Server/LoliServer#341]
**Minecraft Version(我的世界版本) :** {1.16.5}

**LoliServer buildVersion(构建版本) :** {1.16.5 b90f47b}

**Operating System(操作系统) :** {winserver 2012R2 }

**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)

**Mod list(模组列表) :** {1.Abnormals Core  【异常核心-开发者代码】
https://www.mcmod.cn/class/2575.html
2.Abnormals Delight【异常喜悦-食物】
https://www.mcmod.cn/class/3585.html
3.AdvancementPlaques【进展面板】-1.16.5-1.4.0
https://www.curseforge.com/minecraft/mc-mods/advancement-plaques
4.alexsmobs【Alex的生物】-1.12.1
https://www.mcmod.cn/class/3318.html
5.appleskin-forge-mc【苹果皮forge】1.16.x-2.1.0
https://www.mcmod.cn/class/744.html
6.architectury【APL调用】-1.22.32-forge
https://www.mcmod.cn/class/3434.html
7.astikorcarts【马车】-1.16.5-1.1.1
https://www.mcmod.cn/class/3718.html
8.atmospheric【悠然一派】-1.16.5-3.1.0
https://www.mcmod.cn/class/3208.html
9.AttributeFix【属性修复】-1.16.5-10.1.2
https://www.mcmod.cn/class/2264.html
10.AutoRegLib【ARL前置】-1.6-49
https://www.mcmod.cn/class/698.html
11.autumnity【秋原】-1.16.5-2.1.1
https://www.mcmod.cn/class/2412.html
12.bamboo_blocks【竹子制品】-1.16.5-3.0.0
https://www.mcmod.cn/class/3624.html
13.Bayou-Blues【长沼蓝调】-1.16.5-1.0.5
https://www.mcmod.cn/class/4621.html
14.berry_good【甜浆果优化】-1.16.5-4.1.1
https://www.mcmod.cn/class/3480.html
15.BetterAdvancements【更好的进度】-1.16.5-0.1.0.108
https://www.mcmod.cn/class/1530.html
16.BetterCaves-Forge【更好的洞穴】-1.16.4-1.1.2
https://www.mcmod.cn/class/1981.html
17.BetterDungeons【更好的地牢】-1.16.4-1.2
https://www.mcmod.cn/class/26.html
18.betterendforge【更好的末地】-1.16.5-1.6.1
https://www.mcmod.cn/class/3163.html
19.Betterlands【更好的土地】-1.16.5-0.5.0
https://www.curseforge.com/minecraft/mc-mods/betterlands
20.BetterMineshafts-Forge【矿井优化】-1.16.4-2.0.4
https://www.mcmod.cn/class/2788.html
21.BetterStrongholds【要塞重置】-1.16.4-1.2.1
https://www.mcmod.cn/class/3787.html
22.BetterThirdPerson-Forge【第三人称】-1.16.4-1.5.1
https://www.mcmod.cn/class/3492.html
23.Bookshelf-Forge【书架】-1.16.5-10.2.27
https://www.mcmod.cn/class/938.html
24.Bountiful【赏金 悬赏】-1.16.4-3.3.1
https://www.mcmod.cn/class/2657.html
25.buzzier_bees【嗡嗡蜂群 】-1.16.5-3.0.1
https://www.mcmod.cn/class/2326.html
26.byg【BYG你将去的生物群系】-1.3.4
https://www.mcmod.cn/class/1618.html
27.caelus-forge【鞘翅】-1.16.5-2.1.3.1
https://www.mcmod.cn/class/2458.html
29.callablehorses【马匹呼唤】-1.16.3-1.2.1.4
https://www.mcmod.cn/class/3500.html
30.castle_in_the_sky【天空城堡】-1.16.5-0.2.6
31.catalogue【模组目录】-1.3.0-1.16.5
https://www.mcmod.cn/class/3743.html
32.cavebiomeapi【地下生物群系】-1.16.5-1.3.7
https://www.mcmod.cn/class/4534.html
34.cfm【CFM MrCrayfish 的家具】-7.0.0pre22-1.16.3
https://www.mcmod.cn/class/263.html
35.charm-forge【部分改动】-1.16.5-2.3.2
https://www.mcmod.cn/class/2069.html
36.cherishedworlds-forge【存档置顶】-1.16.5-5.1.1.0
https://www.mcmod.cn/class/4228.html
37.chocolate【巧克力】-1.3.0-1.16.4
https://www.mcmod.cn/class/3364.html
38.citadel【Citadel框架】-1.8.1-1.16.5
https://www.mcmod.cn/class/2232.html
39.cleancut-mc【干净利落】1.16-2.2-forge
https://www.mcmod.cn/class/3455.html
40.clickadv【连点器】-1.8
41.ClientTweaks【客户端微调】_1.16.3-5.3.0
https://www.mcmod.cn/class/2012.html
42.cloth-config【屏幕配置API】-4.11.26-forge
https://www.mcmod.cn/class/2346.html
43.Clumps【经验机制改革】-6.0.0.25
https://www.mcmod.cn/class/1499.html
44.collective【代码共享库】-1.16.5-2.58
https://www.mcmod.cn/class/2652.html
45.configured【配置界面】-1.2.0-1.16.3
https://www.mcmod.cn/class/3651.html
46.Controlling【键位冲突显示】-7.0.0.24
https://www.mcmod.cn/class/1191.html
47.corpse【遗体】-1.16.5-1.0.5
https://www.mcmod.cn/class/3007.html
48.CraftTweaker【前置】-1.16.5-7.1.2.411
https://www.mcmod.cn/class/669.html
49.CreativeCore【前置】_v2.2.1_mc1.16.5
https://www.mcmod.cn/class/1283.html
50.cuneiform【前置】-1.16.3-1.2.5
https://www.mcmod.cn/class/3783.html
51.curioofundying-forge【不死图腾插槽】-1.16.5-5.2.0.0
https://www.mcmod.cn/class/2236.html
52.curios-forge【饰品槽】-1.16.5-4.0.5.2
https://www.mcmod.cn/class/2029.html
53.curiouselytra-forge【鞘翅插槽】-1.16.5-4.0.2.3
https://www.mcmod.cn/class/3923.html
54.dungeons_enhanced【地下增强】-1.16.5-1.2
https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced
55.dungeons_plus【新的地牢】-1.16.5-1.1.5
https://www.mcmod.cn/class/3446.html
56.DungeonsArise【地牢浮现之时】-1.16.5-2.1.47-release (2)
https://www.mcmod.cn/class/3607.html
57.DynamicSurroundings【动态环境动态环绕】-1.16.4-4.0.4.2
https://www.mcmod.cn/class/1083.html
58.earthmobsmod【地球暴徒】-1.16.4-0.4.2
https://www.mcmod.cn/class/3891.html
59.EasyMagic【简单附魔】-v1.0.2-1.16.5
https://www.curseforge.com/minecraft/mc-mods/easy-magic
60.EnchantmentDescriptions【附魔描述】-1.16.5-7.0.12
https://www.mcmod.cn/class/1945.html
61.endergetic【末地】-1.16.4-3.0.0
62.Enhanced-Mushrooms【蘑菇增强】-1.16.5-3.0.9
https://www.mcmod.cn/class/3854.html
63.EntityCulling【实体渲染机制优化】-1.16.5-2.1.6
https://www.mcmod.cn/class/3058.html
64.environmental【自然环境】-1.16.5-1.1.0
https://www.mcmod.cn/class/3591.html
65.exoticbirds【珍奇鸟类】-1.16.4-1.2.0
https://www.mcmod.cn/class/1570.html
66.extendedmushrooms【更多蘑菇】-1.6.1-1.16.5+
https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms
67.Fallingleaves【落叶效果】-1.16.3-1.1.1
https://www.mcmod.cn/class/4135.html
68.fancymenu【精美菜单】_2.2.2-2_MC_1.16.2-1.16.5
https://www.mcmod.cn/class/4053.html
69.FarmersDelight【智能农民】-1.16.5-0.4.6
https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant
70.farmersdelightintegration【农夫乐士前置】-1.16.5-1.0.3https://www.mcmod.cn/class/3658.html
71.FastLeafDecay【树叶快速腐烂】-v25
https://www.mcmod.cn/class/1173.html
72.FastWorkbench【工作台性能优化】-1.16.4-4.5.1
https://www.mcmod.cn/class/1486.html
73.ferritecore【铁氧体磁芯 优化模组】-2.0.7-forge
https://www.mcmod.cn/class/3888.html
74.FpsReducer-forge【FPS减速器】-1.23-mc1.16.5
https://www.mcmod.cn/class/1815.html
75.frozenup【冻结】-1.0.1
https://www.curseforge.com/minecraft/mc-mods/frozen-up
76.ftb-backups【FTB备份】-2.1.1.6
https://www.mcmod.cn/class/2127.html
77.ftb-library-forge-【FTB通用前置】1605.3.3-build.71
https://www.mcmod.cn/class/3184.html
78.ftb-quests-forge【FTB任务】-1605.3.5-build.64
https://www.mcmod.cn/class/1423.html
79.ftb-teams-forge【FTB团队】-1605.2.2-build.32
https://www.mcmod.cn/class/3179.html
80.GameMenuModOption【游戏菜单模组设定】-1.16.4-1.8
https://www.mcmod.cn/class/3805.html
90.geckolib-forge【模型动画引擎】-1.16.5-3.0.45
https://www.mcmod.cn/class/3232.html
91.guardvillagers【村民警卫】-1.16.5.1.2.6
https://www.mcmod.cn/class/2686.html
92.Highlighter【高亮】-1.16.5-1.1.0
https://www.curseforge.com/minecraft/mc-mods/highlighter
93.HunterIllager【邪猎者】-1.16.5-1.4.0
https://www.mcmod.cn/class/2735.html
94.Iceberg【支持库】-1.16.5-1.0.8
https://www.curseforge.com/minecraft/mc-mods/iceberg
95.incontrol【生物生成】-1.16-5.2.0
https://www.mcmod.cn/class/3826.html
96.InventoryHud【物品栏HUD+】_[1.16.2-1.16.5].forge-3.4.0
https://www.mcmod.cn/class/3395.html
97.item-filters-forge【物品过滤器】-1605.2.5-build.9
https://www.mcmod.cn/class/1605.html
98.ItemPhysic【物品物理掉落】_v1.4.18_mc1.16.5
https://www.mcmod.cn/class/932.html
99.Jade【玉】-1.16.4-2.7.4
https://www.mcmod.cn/class/3482.html
100.jei【JEI物品管理】-1.16.5-7.7.1.121
https://www.mcmod.cn/class/459.html
101.jeiintegration【JEI扩展】_1.16.5-7.0.1.15
https://www.mcmod.cn/class/2077.html
102.JustEnoughCharacters【通用拼音搜索】-1.16.4-4.3.2
https://www.mcmod.cn/class/840.html
103.JustEnoughProfessions【JEl村民职业工作方块】-1.16.5-1.2.1
https://www.mcmod.cn/class/4464.html
104.JustEnoughResources【JEl显示模组物品】-1.16.5-0.12.1.128
https://www.mcmod.cn/class/2771.html
105.Kiwi【前置库】-1.16.5-3.5.2
https://www.mcmod.cn/class/1290.html
106.KleeSlabs【更好地破坏半砖】_1.16.5-9.2.1
https://www.mcmod.cn/class/1169.html
107.Kobolds【狗头人】-1.4.5
https://www.curseforge.com/minecraft/mc-mods/kobolds
108.konkrete【支持库】_1.3.0_MC_1.16.2-1.16.5
https://www.mcmod.cn/class/4213.html
109.kotlinforforge【模组前置】-1.14.0-obf
https://www.mcmod.cn/class/2890.html
110.LadyLucs+Critter【驯服生物】_Mod_1.3
https://www.curseforge.com/minecraft/mc-mods/ladylucs-critters-mod
111.lazydfu【优化mod】-0.1.3
https://www.mcmod.cn/class/3407.html
112.LibX【lib前置】-1.16.3-1.0.76
https://www.mcmod.cn/class/3207.html
113.logprot【日志保护】-1.16-1.3
114.lootbeams【战利品光束】-1.16.5-release-aug2021
https://www.mcmod.cn/class/4690.html
115.mcw-bridges【灯桥】-1.0.6-mc1.16.5
https://www.curseforge.com/minecraft/mc-mods/light-bridges-illusionary-rails
116.minecolonies【模拟殖民地】-1.0.0-RELEASE-universal
https://www.mcmod.cn/class/682.html
117.morecfm【更多家具】-1.3.1-1.16.3
https://www.mcmod.cn/class/4554.html
118.morevillagers【更多村民】-FORGE-1.16.5-1.5.4
https://www.mcmod.cn/class/4435.html
119.MouseTweaks【鼠标手势】-2.14-mc1.16.2
https://www.mcmod.cn/class/1162.html
120.MushroomQuest【蘑菇探索】_1.16.5_v3.2
https://www.curseforge.com/minecraft/mc-mods/mushroom-quest
121.NaturesCompass【生物群系指南针】-1.16.5-1.9.1-forge
https://www.mcmod.cn/class/754.html
122.neapolitan【那不勒斯风味】-1.16.5-2.1.0
https://www.mcmod.cn/class/3212.html
123.Neat【极简血量显示】+1.7-27
https://www.mcmod.cn/class/619.html
124.NefsMedievalPub【内夫的中世纪装饰】+v9.5Lite(1.16.5)
https://www.curseforge.com/minecraft/mc-mods/neoelfeos-medieval-pub-decoration
125.nethers_delight【下界乐事】-2.1
https://www.mcmod.cn/class/4563.html
126.nether-s-exoticism【下界水果】-1.16.5-1.1.1
https://www.mcmod.cn/class/4320.html
127.notenoughanimations【第三人称修改】-1.2.4
https://www.mcmod.cn/class/4378.html
128.NourishedEndV2【滋养下界】
https://www.curseforge.com/minecraft/mc-mods/nourished-end
129.obfuscate【前置】-0.6.2-1.16.3
https://www.mcmod.cn/class/1217.html
130.OptiFine【高清修复】_1.16.5_HD_U_G8
https://www.mcmod.cn/class/36.html
131.orcinusscaves【奥奇努斯洞穴】-1.3
https://www.curseforge.com/minecraft/mc-mods/orcinuss-caves
132.OreExcavation【矿石挖掘】-1.8.157
https://www.mcmod.cn/class/1955.html
133.OuterEnd【末地群系】-0.2.14
https://www.mcmod.cn/class/4599.html
134.overloadedarmorbar【护甲上限突破】-5.1.0
https://www.mcmod.cn/class/3131.html
135.Patchouli【帕秋莉手册】-1.16.4-53.1
https://www.mcmod.cn/class/1388.html
136.Paxi-Forge【加载模块】-1.16.4-1.0
https://www.mcmod.cn/class/4615.html
137.performant【性能优化】-1.16.2-5-3.72m
https://www.mcmod.cn/class/2385.html
138.personality【更多动作】-1.16.5-1.0.2
https://www.mcmod.cn/class/3610.html
139.Piglin+Expansion【猪灵拓展】+1.0
https://www.curseforge.com/minecraft/mc-mods/piglin-expansion
140.Placebo【前置】-1.16.5-4.6.0
https://www.mcmod.cn/class/1023.html
141.polymorph-forge【多态合成】-1.16.5-0.25
https://www.mcmod.cn/class/2895.html
142.projectvibrantjourneys【活力之旅】-1.16.5-3.2.9
https://www.mcmod.cn/class/1564.html
143.Quark【夸克】-r2.4-316
https://www.mcmod.cn/class/527.html
144.quickhomes【快速回家】-1.16.3-1.2.6
https://www.curseforge.com/minecraft/mc-mods/quickhomes
145.quickteleports【快速传送】-1.16.2-1.1.2
https://www.curseforge.com/minecraft/mc-mods/quickteleports
146.randompatches【随意修复】-2.4.4-forge
https://www.mcmod.cn/class/2253.html
147.ReAuth【无效重启】-1.16-Forge-3.9.3
https://www.mcmod.cn/class/1520.html
148.repurposed_structures_forge【结构变体】-3.2.3+1.16.5
https://www.mcmod.cn/class/4518.html
149.RevampedWolf【更好的狼】-1.16.4-0.7.1
https://www.mcmod.cn/class/3559.html
150.sapience【更好的猪灵】-1.16.5-1.1.2
https://www.mcmod.cn/class/3568.html
151.SaveMyStronghold【要塞修复】-1.16.4-1.0
https://www.mcmod.cn/class/3459.html
152.seals【海豹展示】-1.16.3-2.1.2
https://www.curseforge.com/minecraft/mc-mods/seals
153.selene【运行库】-1.16.5-1.6.1
https://www.mcmod.cn/class/4159.html
154.SereneSeasons【静谧季节】-1.16.5-4.0.1.121-universal
https://www.mcmod.cn/class/1132.html
155.simpledelights【简单灯光】-1.1
156.simplefarming【简单农业】-1.16.5-1.3.8
https://www.mcmod.cn/class/1874.html
157.simplylight【更好的灯】-1.16.4-1.2.0-build.11
https://www.mcmod.cn/class/2318.html
158.simplytea【简单的茶】-1.16.5-2.4.0
https://www.mcmod.cn/class/3597.html
160.sit【席地而坐】-1.16.5-v1.3.1
https://www.mcmod.cn/class/1656.html
170.smallships【帆船】-1.16.5-1.10.1
https://www.mcmod.cn/class/4683.html
171.Snow_Pig【冷冻猪】-1.16.5-2.3.1、
https://www.curseforge.com/minecraft/mc-mods/snow-pig
172.SoL-Carrot【生活调味胡萝卜】-1.16.5-1.10.1
https://www.mcmod.cn/class/1836.html
173.sophisticatedbackpacks【精妙背包】-1.16.5-3.2.12.337
https://www.mcmod.cn/class/3739.html
174.spark-forge【性能分析】
https://www.mcmod.cn/class/4073.html
175.SpawnerFix【刷怪笼修复】-1.16.2-1.0.0.2
https://www.curseforge.com/minecraft/mc-mods/spawner-fix
176.Spheric【球形】+1.0.5+1.16.5
https://www.curseforge.com/minecraft/mc-mods/spheric
177.stoneholm【地下村庄】-1.2.2
https://www.mcmod.cn/class/4277.html
178.structure_gel【结构API】-1.16.5-1.7.7
https://www.mcmod.cn/class/3033.html
179.structurize【结构化】-0.13.219-ALPHA-universal
https://www.mcmod.cn/class/1865.html
180.TerraForged【真实地形生成】-1.16.5-0.2.15
https://www.mcmod.cn/class/2555.html
181.terraincognita【未知之地】-1.16.3-1.6.4.2
https://www.mcmod.cn/class/3784.html
182.Tips【提示】-1.16.5-4.0.7
https://www.mcmod.cn/class/3666.html
183.Toast-Control【消息框控制】-1.16.4-4.3.1
https://www.mcmod.cn/class/1758.html
184.toms_storage【汤姆的简易存储】-1.2.18
https://www.mcmod.cn/class/2882.html
185.torchmaster【火炬大师】-2.3.8
https://www.mcmod.cn/class/779.html
186.towers_of_the_wild【旷野之塔】-1.16.4-2.0.1
https://www.mcmod.cn/class/2892.html
187.TRansliterationLib【模组优化】-1.0.4
https://www.mcmod.cn/class/4374.html
188.travelers_index【旅行指数】-1.16.4-1.0.2
https://www.curseforge.com/minecraft/mc-mods/travelers-index
189.TravelersTitles【RPG标题】-1.16.4-1.5
https://www.mcmod.cn/class/4471.html
190.TreeChop【砍树】-1.16.4-0.14.5
https://www.mcmod.cn/class/1294.html
191.unnamedanimalmod【无名动物】-1.0.2
https://www.curseforge.com/minecraft/mc-mods/unnamed-animal-mod
192.upgrade_aquatic【碧海新生】-1.16.5-3.1.0
https://www.mcmod.cn/class/2916.html
193.valhelsia_core【API前置】16.0.10
https://www.mcmod.cn/class/4003.html
194.valhelsia_structures【生成结构】-1.16.5-0.1.5
https://www.mcmod.cn/class/2768.html
195.villagernames【村庄名字】_1.16.5-3.3
https://www.mcmod.cn/class/2070.html
196.villagespawnpoint【村庄出生点】_1.16.5-1.8
https://www.mcmod.cn/class/2030.html
197.Waystones【传送石碑】_1.16.5-7.6.3
https://www.mcmod.cn/class/1339.html
198.worldedit-mod【创世神】-7.2.5-dist
https://www.mcmod.cn/class/609.html
199.Xaeros_Minimap【Xaero的小地图】_21.16.0_Forge_1.16.5
https://www.mcmod.cn/class/1701.html
200.XaerosWorldMap【Xaero的世界地图】_1.17.0.1_Forge_1.16.5
https://www.mcmod.cn/class/1483.html
201.xptome【经验书】-1.16.5-v2.1.2
https://www.mcmod.cn/class/2118.html
202.YungsApi【Yangs前置】-1.16.4-Forge-12
https://www.mcmod.cn/class/3372.html
203.YungsExtras-Forge【Yungs的原版增强】-1.16.4-1.0}

**Plugin list(插件列表) :** {AuthMe,LiteTeleport,openInventory}
**Description of issue(描述) :** {The same problem occurred last time, that is, when the server is on, enter stop to restart, and then it can't be opened again. When it is opened, it will flash back}

**Comment by Kotori0629** [comment]
我不太理解你想表达什么。 或许你可以上传一个Video, 或者给我详细的Log
