### ISSUE TITLE
[1.16] FTB ranks compatibility issues

### ISSUE THREAD

**Issue by akong201** [Loli-Server/LoliServer#344]
**Minecraft Version(我的世界版本) :1.16.5

**LoliServer buildVersion(构建版本) : LoliServer-1.16.5-132db0e-server.jar

**Operating System(操作系统) : Windows server 2022

**Concerned mod / plugin(有关的插件/Mod) : FTB ranks

**Logs : None

**Steps to Reproduce(复现步骤) :**
install FTB ranks in loliserver.
仅安装 ftb ranks

**Description of issue :** 
Im running ATM6 on loli server, the ftb ranks seems not working properly. Its a permission control mod. I have tested it in pure forge server and it is working.  i guess its because of the default bukkit permission control function.  the bukkit one override the the mod one.
我正在用loliserver开ATM6的包，包内的权限管理mod，ftb ranks没能正常的控制玩家权限。我在纯forge 服务器测试过这个mod，可以正常运行并控制权限。我个人猜测的的原因是 默认bukkit有权限管理的功能，然后它优先级高于模组的优先级，所以这个mod没法正常工作。

**Comment by Kotori0629** [comment]
你很聪明，Bukkit的权限系统取代了原版, 目前没有特别好的办法能处理这个问题

**Comment by SirOMGitsYOU** [comment]
The easiest way to resolve this is just to install luckperms then you can grant the default permissions for ftb teams etc

**Comment by Kotori0629** [comment]
> The easiest way to resolve this is just to install luckperms then you can grant the default permissions for ftb teams etc

Or give player permission:  minecraft.command.ftbteams
