### ISSUE TITLE
[1.16] EssentialsX does not work

### ISSUE THREAD

**Issue by dayd21git** [Loli-Server/LoliServer#345]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-132db0e-server.jar

**Operating System(操作系统) :** Linux(Debian11)

**Concerned mod / plugin(有关的插件/Mod) :** [https://www.spigotmc.org/resources/essentialsx.9089/download?version=431651](https://www.spigotmc.org/resources/essentialsx.9089/download?version=431651)

**Logs :** [https://pastebin.com/StG0h10r](https://pastebin.com/StG0h10r)

**Steps to Reproduce(复现步骤) :**
 1. Install server and plugin
 2. Start server

**Description of issue :** I'm running your server with a plugin and the plugin commands don't work

**Comment by XionioXMaster** [comment]
Use Cmi, this better and good work. EssentialsX does not recommend using yourself on mod servers

**Comment by dayd21git** [comment]
> Cmi

Maybe you're right. However, there is no similar problem on the Mohist core.

**Comment by Kotori0629** [comment]
Essentials 不能得到很好的工作, 建议更换CMI或者其他相同功能的

**Comment by Xplodin** [comment]
cmi throws too many errors.
especially on 1.16
Essentialsx dev updates work

**Comment by dayd21git** [comment]
> cmi throws too many errors. especially on 1.16 Essentialsx dev updates work

Thanks, I'll try
