### ISSUE TITLE
Can't open Curios GUI before dying or travelling another world

### ISSUE THREAD

**Issue by ImMAils** [Loli-Server/LoliServer#346]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 1.16.5-b90f47b

**Operating System(操作系统) :** Linux

**Logs :** 

**Mod list(模组列表) :** 68 [treechop, alexsmobs, shrines, locks, jei, abnormals_core, mekanism, caelus, create, bettercaves, mgui, roadrunner, citadel, sereneseasons, yungsapi, dungeoncrawl, improvedbackpacks, endergetic, randompatches, relics, walljump, dynview, carryon, crafttweaker, immersivepetroleum, crumbs, forge, supplementaries, emotecraft, selene, infernalmobs, corpse, antiqueatlas, minecraft, tconstruct, wildfire_gender, psi, immersiveengineering, biomesoplenty, endrem, valhelsia_structures, modifiers, forbidden_arcanus, yungsbridges, botania, spark, flywheel, curios, savageandravage, patchouli, mantle, quark, croptopia, kryptonreforged, flowingagony, autoreglib, blockcarpentry, xercapaint, hardcorerevival, enigmaticlegacy, cfm, architectury, ferritecore, extrabotany, observerlib, cloth-config, smallships, cosmeticarmorreworked, valhelsia_core, bettermineshafts]

**Plugin list(插件列表) :** Plugins (13): SmoothSleep, LightPerms, SkinsRestorer, LWP, Fix4Log4J, PlaceholderAPI, BanItem, ClearLag, NametagHide, Invsee, SimpleSit, DiscordSRV, AutoRestart

**Description of issue(描述) :** 

I can't open my Curios inventory before i die or travell another world 

https://user-images.githubusercontent.com/45512165/154967013-6f7b7db1-c89e-4825-a886-d7c709a17766.mp4
(Fixing it with travelling another world. My /c-r command doing the same thing, teleports player to the nether and to the overworld again)

https://user-images.githubusercontent.com/45512165/154967237-ae99de97-d74c-4074-9013-c55eb4557aac.mp4
(Fixing it by dying)

**Comment by Kotori0629** [comment]
Contact mod author, is not LoliServer bug
