### ISSUE TITLE
Weird issue.

### ISSUE THREAD

**Issue by KubiRemPL** [Loli-Server/LoliServer#347]
I am getting this weird issue with latest Loliserver + Flamecord. There was no issue at all when we were using Velocity.
[ISSUE.txt](https://github.com/Loli-Server/LoliServer/files/8117268/ISSUE.txt)

**Comment by XionioXMaster** [comment]
Compose the issuge the way you want!

**Comment by KubiRemPL** [comment]
What do you mean? What should I do?

**Comment by XionioXMaster** [comment]
Customize your theme! We will not solve such nonsense
