### ISSUE TITLE
ArtMap 无法正常使用，虚拟机控制台出现报错

### ISSUE THREAD

**Issue by ybquality** [Loli-Server/LoliServer#35]
ArtMap地址：https://gitlab.com/BlockStack/ArtMap     （插件需要前置：ProtocolLib）
报错信息：https://paste.ubuntu.com/p/C3Nm46Cpmm/
插件可正常加载，能够正常打开插件gui界面，玩家进入游戏后出现**报错信息**内报错
画架可正常放置，画布无法正常放置在画架上（控制台出现报错信息）

**Comment by Kotori0629** [comment]
Does this plug-in work in PaperSpigot？

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/119365846-f12fbb00-bce2-11eb-8433-56e762c9293c.png)

Fixed: Setting "background compiler: false" to ../plugins/ProtocolLib/config.yml
