### ISSUE TITLE
[1.16] Doesnt boot server with the_vault mod from vault hunters official

### ISSUE THREAD

**Issue by Xplodin** [Loli-Server/LoliServer#351]
**Minecraft Version(我的世界版本) :** Minecraft version
 1.16.5
**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-******-server.jar"
LoliServer-1.16.5-132db0e-server.jar
**Operating System(操作系统) :** Provide the name of your OS
Ubuntu 20
**Concerned mod / plugin(有关的插件/Mod) :** Provide mod / plugin name and download link if possible
the_vault mod
**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
https://logs.panel.gg/140c6a4f19816c2fa1ff1e4b251cccc5
**Steps to Reproduce(复现步骤) :**
 1. Install vault hunters modpack
 2. Install Loliserver
 3. crash

**Description of issue :** Give all details about your issue
Seems to be related to mixins for override max repair levels

**Comment by Kotori0629** [comment]
Where should I get this mod?

**Comment by Xplodin** [comment]
https://www.curseforge.com/minecraft/modpacks/vault-hunters-official-modpack

that is the exact pack im using with the mod. the mod itself is also on CF called the_vault-1.7.2p1.12.4

**Comment by Kotori0629** [comment]
This mod cannot work in forge_server, forge-36.2.19-server

**Comment by Kotori0629** [comment]
Contact mod author.
