### ISSUE TITLE
[1.16] 林业工作台无法使用

### ISSUE THREAD

**Issue by ddaodan** [Loli-Server/LoliServer#352]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** 1.16.5-b3d757c

**Operating System(操作系统) :** Linux (amd64) version 3.10.0-1127.el7.x86_64

**Concerned mod / plugin(有关的插件/Mod) :** Forestry林业

**Logs :** [crash report](https://gist.github.com/ddaodan/6695cec7bece6bcf2991280c5e66cc68)

**Steps to Reproduce(复现步骤) :**
 1. 合成一个林业的工作台
 2. 放在地上
 3. 右键，无法打开

**Description of issue :** 林业的工作台无法使用，做出来放到地上右键打不开，放下之后背包里还有，无法破坏（破坏后走到那个格子会被回弹），用/setblock也无法清除
![image](https://user-images.githubusercontent.com/40017293/158994188-2e22b4f1-0333-4577-a267-07ed48c4cc08.png)
单机测试无此问题

**Comment by Kotori0629** [comment]
找作者
