### ISSUE TITLE
AI mobs no working

### ISSUE THREAD

**Issue by MrJorman** [Loli-Server/LoliServer#357]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** This server is running LoliServer version 1.16.5-1e51f20 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.31)

**Operating System(操作系统) :** Windows 10

**Logs :** no logs

**Mod list(模组列表) :** [quarkoddities, quarkfix, betterdungeons, alexsmobs, buzzier_bees, infernalexp, berry_good, morecreatestuffs, limitedchunks, jei, portalblocker, enhanced_mushrooms, attributefix, architects_palette, abnormals_core, bayou_blues, expanvils, upgrade_aquatic, curiosquarkobp, better_badlands, extraboats, bettercaves, create, mcwpaintings, citadel, artifacts, farmersdelightintegrations, configured, yungsapi, outer_end, maxhealthfix, decorative_blocks, environmental, respawningshulkers, bamboo_blocks, endergetic, randompatches, lazydfu, eventhelper, dynview, allurement, crafttweaker, miningmaster, caverns_and_chasms, ninjaphenix_container_lib, dragonfight, forge, twilightforest, supplementaries, experiencebugfix, nether_extension, neapolitan, selene, chocolate, minecraft, logprot, farmersdelight, repurposed_structures, twilightdecor, abundance, seeker_compass, createtweaker, decorative_blocks_abnormals, atmospheric, mostructures, flywheel, curios, savageandravage, quark, collective, autumnity, autoreglib, abnormals_delight, yungsextras, performant, twilight_bosses_respawn, betterstrongholds, muchmoremodcompat, expandedstorage, nethers_delight, ferritecore, chimes, moredragoneggs, fastleafdecay, expandability, bettermineshafts]

**Plugin list(插件列表) :** Plugins (18): LuckPerms, PhantomSMP, PlaceholderAPI, UltimateAutoRestart, IllegalStack, WorldBorder, HolographicDisplays, Vault, WorldEdit, EntityTrackerFixer, AdvancedBan, TAB, MyHome, WorldGuard, WGExtender, BetterRTP, CMILib, CMI

**Description of issue(描述) :** animals and monsters die and don't move anymore, the problem is in the core - I checked and removed all mods and plugins - the problem remained. As soon as I changed the core, the mobs worked again.
![image](https://user-images.githubusercontent.com/55187962/160288837-9a829074-6ae5-4263-b2d6-2b98f5516f6f.png)
![image](https://user-images.githubusercontent.com/55187962/160288843-101a59db-427c-4644-b4bf-6c21b0a097fc.png)

**Comment by MrJorman** [comment]
I still don't understand why this happens, but when there are more than 20 people online or the MS server is equal to 30, their AI dies. /forge tps/

**Comment by MrJorman** [comment]
and **water bucket** place in WorldGuard private. - it's bug

**Comment by MrJorman** [comment]
also in someone else's private where PVP is turned off, you can break the shield

**Comment by MrJorman** [comment]
@Kotori0629 bro, help.

1. WorldBorder is not working correctly in other worlds, see my topic: https://github.com/Loli-Server/LoliServer/issues/330
2. BUG placed BED in WorldGuard privates: https://github.com/Loli-Server/LoliServer/issues/343
3. Buckets of water, lava and all the rest can pour out someone else's private WorldGuard.
4. Shield players in private WorldGuard where PVP is turned off can break.
5. Mobs AI in World - broken, they just stand still and can't move their intelligence - died, I deleted all mods and plugins - it didn't help when I changed the core - it was fixed.

**Comment by MrJorman** [comment]
These are probably the most critical bugs on your kernel, fix them and the kernel will be perfect.

**Comment by XionioXMaster** [comment]
I agree, I noticed this problem on my server, I don’t understand what it is connected with, but it exists. Possibly related to unloading entities from a chunk. In any case, if you move a world with a similar entity to a pure Forge, it comes to life and continues to move

**Loliserver**: I forgot to clarify, AI entities will not recover even if you remove all modifications

**Comment by Kotori0629** [comment]
How can I repeat it ?

**Comment by MrJorman** [comment]
Come to my server, I'll show you to repeat it, I do not know what needs to be done.

**Comment by MrJorman** [comment]
Mobs/monsters die themselves and only in the ordinary world, in other worlds they don't seem to AI die.

**Comment by MrJorman** [comment]
Usually this happens when the server is loaded, then their intelligence dies and is no longer restored. Even if the horse's intelligence dies, you can't get off and sit down.

**Comment by MrJorman** [comment]
Previously, this problem did not exist, it appeared after your updates for a long time

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/160346711-3ba25a22-3f7b-4aed-a124-17b4689df06c.png)
For example, the player has a farm, all mobs have intelligence died, they can't do anything.

**Comment by MrJorman** [comment]
I asked the players, they say that in hell, in the edge, in the twilight forest (mod) - everything is OK, only in the ordinary world mobs lose their intelligence and die standing on the 1st place.

**Comment by Kotori0629** [comment]
> ordinary world

Ordinary world? What's this? World? DIM1? DIM-1? Are there any other worlds created using multiverse?

**Comment by Kotori0629** [comment]
> I asked the players, they say that in hell, in the edge, in the twilight forest (mod) - everything is OK, only in the ordinary world mobs lose their intelligence and die standing on the 1st place.

Only in main world?

**Comment by MrJorman** [comment]
this bug works without plugins and without mods, on a clean core.

**Comment by MrJorman** [comment]
world (normal world) (main)

**Comment by Kotori0629** [comment]
> 

I test now.

**Comment by MrJorman** [comment]
It is unlikely that you will succeed, you need to create a load on the server, well, try to load chunks or look for villages, especially in villages it turns out. Or sleep a lot of different mobs and try to get out of chunks, maybe it will work, try to restart the server 2-3 times and see.

**Comment by Kotori0629** [comment]
> It is unlikely that you will succeed, you need to create a load on the server, well, try to load chunks or look for villages, especially in villages it turns out. Or sleep a lot of different mobs and try to get out of chunks, maybe it will work, try to restart the server 2-3 times and see.

Does this problem exist in other kernels, such as Mohist?

**Comment by MrJorman** [comment]
No, I haven't.

**Comment by MrJorman** [comment]
Your kernel didn't have this problem before either, it appeared after updates, but I don't even know after which ones.

**Comment by Kotori0629** [comment]
![B~JQ) ~68YWT`I)Y71588WJ](https://user-images.githubusercontent.com/81866089/160350819-b5b4c863-74a3-48fe-977e-f4e2140ce5f2.png)
Remove

**Comment by Kotori0629** [comment]
I didn't repeat this problem..

**Comment by MrJorman** [comment]
NO!

**Comment by MrJorman** [comment]
I'm telling you again, the bug works without mods and plugins.

**Comment by MrJorman** [comment]
I have already removed all plugins and all mods, went to the map and the problem remained. Previously, this plugin also stood on your core and there was no problem with dead mobs.

**Comment by Kotori0629** [comment]
> I'm telling you again, the bug works without mods and plugins.
At present, I have not reproduced this problem

**Comment by MrJorman** [comment]
you will not produce it, it works where there is online and server load.

**Comment by Kotori0629** [comment]
> 

My server have 46 onlines.

**Comment by MrJorman** [comment]
Are you using the latest core?

**Comment by Kotori0629** [comment]
> 

Yes

**Comment by MrJorman** [comment]
Well, look, I won't lie to you, even @XionioXMaster confirms that he has the same problem!

**Comment by MrJorman** [comment]
Just think about why when mobs die - I change the core to pure Forge and they come to life again.

**Comment by MrJorman** [comment]
By the way, it seems that when I put Mohist, they were also dead when transferring the world.

**Comment by Kotori0629** [comment]
> By the way, it seems that when I put Mohist, they were also dead when transferring the world.

F**k

**Comment by MrJorman** [comment]
You didn't understand, it was when mobs hung on your core, I decided to take the map and transfer it to Mohist, they didn't seem to decompose there either, and when I transferred it to Forge, everything decomposed. I tested it that way then.

**Comment by Kotori0629** [comment]
> You didn't understand, it was when mobs hung on your core, I decided to take the map and transfer it to Mohist, they didn't seem to decompose there either, and when I transferred it to Forge, everything decomposed. I tested it that way then.

I know

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/160352351-0f62385e-b170-49da-a227-7a2f436d4c97.png)
I deleted EntityTrackFixer, nothing has changed

**Comment by Kotori0629** [comment]
> ![image](https://user-images.githubusercontent.com/55187962/160352351-0f62385e-b170-49da-a227-7a2f436d4c97.png) I deleted EntityTrackFixer, nothing has changed

Will they get hurt when you attack them？

**Comment by MrJorman** [comment]
yes.

**Comment by MrJorman** [comment]
they will take damage, as well as the recoil from my blow.

**Comment by MrJorman** [comment]
Even mobs from the mod also lose their intelligence. (Alex'sMobs)

**Comment by MrJorman** [comment]
oddly enough, in other worlds and in the twilight forest - everything is OK.

**Comment by MrJorman** [comment]
@Kotori0629 also, please fix it, it works on all servers

1. WorldBorder is not working correctly in other worlds, see my topic: https://github.com/Loli-Server/LoliServer/issues/330
2. BUG placed BED in WorldGuard privates: https://github.com/Loli-Server/LoliServer/issues/343
3. Buckets of water, lava and all the rest can pour out someone else's private WorldGuard.
4. Shield players in private WorldGuard where PVP is turned off can break.
5. Mobs AI in World - broken, they just stand still and can't move their intelligence - died, I deleted all mods and plugins - it didn't help when I changed the core - it was fixed.
6. Bamboo blocks grows down by 1 block

**Comment by MrJorman** [comment]
Players also complain that things disappear earlier after death, that is, even 5 minutes do not pass before things disappear.

**Comment by MrJorman** [comment]
AI mobs - fixed. i Delete plugin EntityTrackerFixer.

**Comment by MrJorman** [comment]
@Kotori0629 also, please fix it, it works on all servers

1. WorldBorder is not working correctly in other worlds, see my topic: https://github.com/Loli-Server/LoliServer/issues/330
2. BUG placed BED in WorldGuard privates: https://github.com/Loli-Server/LoliServer/issues/343
3. Buckets of water, lava and all the rest can pour out someone else's private WorldGuard.
4. Shield players in private WorldGuard where PVP is turned off can break.

5, Bamboo blocks grows down by 1 block
6. Players also complain that things disappear earlier after death, that is, even 5 minutes do not pass before things disappear.
