### ISSUE TITLE
What means “we need peace and love” ?

### ISSUE THREAD

**Issue by SvechuYasno** [Loli-Server/LoliServer#366]
**Is your Suggestion related to a problem? Please describe.(建议是否与问题有关？请描述)**
When I started server works, I have a problem with my friends don’t can connect with me, we don’t support wars and also just want peace, but we are faced with this inscription in the console.

**Describe the solution you'd like(描述你想要的解决方案)**
I understand this inscription is simply because we are Russians, then how do you explain this racism and politics in a place where it should not be, if you do not understand that Russians do not want war, then I feel sorry for you and I hope you reconsider your racist views

**Additional context(附加)**
![AE12EA48-4DA4-4230-8536-974BB2958FD2](https://user-images.githubusercontent.com/102958818/161525097-93596650-cc62-4e0a-8818-29076988e91b.png)

**Comment by Kotori0629** [comment]
thank, we'll fix it
