### ISSUE TITLE
[1.16] Projectile Mechanic Broken

### ISSUE THREAD

**Issue by iSoul-Es** [Loli-Server/LoliServer#367]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** Provide LoliServer  buildVersion: "LoliServer-1.16.5-9251c7c-server.jar"

**Operating System(操作系统) :** Tested in Windows 10 (same in linux)

**Concerned mod / plugin(有关的插件/Mod) :** MythicMobs and MythicLib

**Logs :** https://paste.loliidc.cn/?f0fb7333aec05e04#H938kfTo6vbEzcwm42w3N2gHPRoQYZ4VnpYUsWVXWTCP

**Steps to Reproduce(复现步骤) :**
 1. 
MythicMobs Mob File: https://pastebin.com/t1yiABzf (copy into ExampleMobs.yml)
MythicMobs Skill File: https://pastebin.com/NvyPbRdV (copy into ExampleSkills.yml)
 /mm reload
 
 2.
 give the custom mob with projectile mechanic in this example i use "test mob".. then..  /mm egg get TestMob
 right click to use and set you on gamemode Survival
 
 3. 
 skill should be executed on hit. but it doesn't happen and instead every time the mob hits an error appears

**Description of issue :** i use MythicMobs premium version and MythicLib 1.4
with java 16 (Mythiclib and MM needs java 16)
 i provide here the plugins (you can do with an antivirus or with what you want if you do not trust)
 
[MM and ML.zip](https://github.com/Loli-Server/LoliServer/files/8447528/MM.and.ML.zip)

**Comment by Kotori0629** [comment]
I think this problem has been fixed. If there is still a problem, please reopen an issue

**Comment by iSoul-Es** [comment]
Okei!! Thnx

**Comment by Kotori0629** [comment]
Jenkins: [Jenkins](https://cdn.ci.loliidc.cn:30011/job/LoliServer-1.16.5/10/artifact/projects/LoliServer/build/libs/LoliServer-1.16.5-37fc965-server.jar)
