### ISSUE TITLE
The server could not be started

### ISSUE THREAD

**Issue by yagaoyg** [Loli-Server/LoliServer#368]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-dd054d5-server

**Operating System(操作系统) :** Windows 10 20H2

**Description of issue(描述) :** it doesn't work
![{3$ U 2}K@A3U9Q~3ZBA7KK](https://user-images.githubusercontent.com/103345058/162599368-4f415a7f-5f13-4ced-9ac5-462d9c3378c9.png)

![G43R@96 @ `4TAXEQ7V _EP](https://user-images.githubusercontent.com/103345058/162599445-cc29d3fd-a6d1-4415-8498-eabacbd5c1cb.png)

**Comment by Kotori0629** [comment]
Update LoliServer version
