### ISSUE TITLE
craftbukkit 不运行

### ISSUE THREAD

**Issue by deekyhpc** [Loli-Server/LoliServer#374]
**Minecraft Version(我的世界版本) :** {Minecraft version}1.16.5

**LoliServer buildVersion(构建版本) :** {Provide LoliServer build number}LoliServer-1.16.5-b35e5c7

**Operating System(操作系统) :** {Provide the name of your OS}win10

**Logs :** {Link(s) of logs and crash reports if you have}, (https://paste.loliidc.cn)https://paste.ubuntu.com/p/MVqsMV3sY6/

**Mod list(模组列表) :** {List of your mods. You can also use /getmodlist command on your server}

**Plugin list(插件列表) :** {List of your plugins. You can also use /getpluginlist command on your server}

**Description of issue(描述) :** {Give all details about your issue}加载模组之后会提示bukkit没有运行，把模组全部删掉就没有任何问题

**Comment by Kotori0629** [comment]
某个模组中携带了 snakeyaml库 ， 与Bukkit的snakeyaml存在版本差异，自行排查mod

**Comment by deekyhpc** [comment]
> 某个模组中携带了 snakeyaml库 ， 与Bukkit的snakeyaml存在版本差异，自行排查mod

多谢了！awa
