### ISSUE TITLE
[1.16] NoClassDefFoundError at Titanium library

### ISSUE THREAD

**Issue by Tomut0** [Loli-Server/LoliServer#375]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** LoliServer-1.16.5-37fc965-server.jar

**Operating System(操作系统) :** Oracle Linux 7.9

**Concerned mod / plugin(有关的插件/Mod) :** [Titanium](https://www.curseforge.com/minecraft/mc-mods/titanium)

**Logs :** 
[paste.loliidc.cn](https://paste.loliidc.cn/?8b9eebae9fe52805#GydnhBawpWfJ7Yaa8MqvBd8WbB7AZyzH52SGnMQ9GyoT)
[paste.ubuntu.com](https://paste.ubuntu.com/p/hgS3MD5fVf/)

**Steps to Reproduce(复现步骤) :**
It seems, the problem appears using Industrial-Foregoing liquid mechanisms, 
but I can't reproduce it right now. 🤔 

**Description of issue :** 
Titanium is used as library of [Industrial-Foregoing](https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/blob/1.16/src/main/resources/META-INF/mods.toml#L30) mod on my server.

**Comment by Kotori0629** [comment]
Don't installed this in server
