### ISSUE TITLE
[1.16] mysql-connector outdated

### ISSUE THREAD

**Issue by Sylensky** [Loli-Server/LoliServer#377]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) : This server is running LoliServer version 1.16.5-9aeb07e (MC: 1.16.5)

**Operating System(操作系统) :**  Debian Linux

**Concerned mod / plugin(有关的插件/Mod) :** ChatControl - Red https://www.mc-market.org/resources/18217/

**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
 https://paste.loliidc.cn/?d77b86ea079bfa46#9ioFoFoJrUXuQABuwtPhhz63UDjd18WLh8Uy7xDtvLjz

**Steps to Reproduce(复现步骤) :**
 1. download latest build from jenkins
 2. use latest chat control red plugin
 3. start the server and observe the error

**Description of issue :**
It seems the mysql-connector-java library is very outdated. I previously used on catserver the version `8.0.28` and loliserver uses `5.1.49`.
It works fine with `8.0.28`.

**Comment by Kotori0629** [comment]
If it is updated, the application loaded with outdated jdbc driver will be broken

**Comment by Sylensky** [comment]
what should i do in that case?

**Comment by Kotori0629** [comment]
> what should i do in that case?

CatServer used 8.0.28 ?

**Comment by Kotori0629** [comment]
Sorry, I just checked MySQL connector. The new version includes the new version and the old version. You will receive the loliserver update push soon
