### ISSUE TITLE
[1.16] ChatControl-Red support

### ISSUE THREAD

**Issue by Sylensky** [Loli-Server/LoliServer#378]
**Minecraft Version(我的世界版本) :** 1.16.5

**LoliServer buildVersion(构建版本) :** This server is running LoliServer version 1.16.5-357bf2c (MC: 1.16.5)

**Operating System(操作系统) :** Debian Linux

**Concerned mod / plugin(有关的插件/Mod) :** ChatControl-Red

**Logs :** Link(s) of logs and crash reports if you have, (https://paste.loliidc.cn)
![image](https://user-images.githubusercontent.com/57076968/164258588-3ec00c08-72f1-422d-a005-4f5994700023.png)
https://paste.loliidc.cn/?158e3486f4e2ddd1#CgtLP5crkmKQ6F7aotMEAWVhkFrauxrB1bnFvQNRTKWV

**Steps to Reproduce(复现步骤) :**
Nothing much to say here except the necessary libraries shown below aren't loaded because they dont exist.

**Description of issue :** 
ChatControl-Red is not fully compatible with LoliServer and therefor crashes the server.  Iam not sure if the `spongepowered` related logs are caused because of the missing libraries or the latest addition of the mysql connector.

**Comment by Sylensky** [comment]
Sorry the screenshot might be confusing. It shows what libraries are loaded when the plugin fully works.

**Comment by Kotori0629** [comment]
It is neither incompatible with chatcontrol red nor the newly added library. You can delete byg mod and you will find that everything works

**Comment by Kotori0629** [comment]
It is neither incompatible with chatcontrol red nor the newly added library. You can delete byg mod and you will find that everything works
