### ISSUE TITLE
[1.16] WorldGuard and any Bucket with any liquid or empty

### ISSUE THREAD

**Issue by Sleepwalkerx** [Loli-Server/LoliServer#379]
Minecraft Version(我的世界版本) : 1.16.5
LoliServer buildVersion(构建版本): LoliServer-1.16.5-132db0e-server
Operating System(操作系统) : Linux and Windows
Concerned mod / plugin(有关的插件/Mod) : WorldGuard and WorldEdit

Steps to Reproduce(复现步骤) :
 1. Install the WorldGuard plugin on your server and ask a friend to create a private region where you can't break blocks or interact with anything.
 2. Try pouring any liquid from any bucket on this region
 3. You will see that even though you do not have rights, you pour out the liquid.

Description of issue : The problem is that buckets ignore private and you can use them to grieve. I tried it on the Spigot server and there I can't pour a bucket of water on someone else's private, but on LoliServer it works. That is, I use the usual default WorldGuard settings and the private region is ignored.

**Comment by Kotori0629** [comment]
Duplicated #362
