### ISSUE TITLE
Quark 与 WorldEdit

### ISSUE THREAD

**Issue by KMRuri** [Loli-Server/LoliServer#45]
测试服务器核心版本：LoliServer-1.16.5-83b9fa6-server

mod版本：
Quark-r2.4-312
AutoRegLib-1.6-49
worldedit-mod-7.2.5-dist

插件版本：
worldedit-bukkit-7.2.5-dist

以下均为单独测试，无其他多余的插件或mod，测试结果：
mod版本的WE在服务器中无效果（服务器与客户端均有装）。
插件版本的WE单独测试在服务器中运行正常。
但，加入Quark后，插件版本的WE的/up指令（例：/up 1，/up 0）会出现问题，不能使用，并会在游戏中提示：You would   hit something above you.（即使你的上方空无一物没有任何方块）
客户端单人游戏测试Quark+mod版WE，没有上述问题。

以及一个我不知道能不能算是BUG的疑问：
插件版的WE无法识别mod方块，但这有可能和MV在bukkit+forge下无法识别mod维度世界一样，所以我无法判断该问题是否属于bug。（在一些mod版WE能够生效的端里，mod版WE倒是可以识别mod方块。）

**Comment by Kotori0629** [comment]
This is hybrid Server Bug . At present, there is no good repair method

**Comment by Kotori0629** [comment]
Fixed Worldedit Error
